#!/usr/bin/env python3
"""Build native agent definitions from the maintained roles and shared rules."""
import argparse
import json
from pathlib import Path
import re
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
NAMES = {"jackson", "sylvia", "nikhil", "taichi", "brendan", "glyndon", "hannah"}


def read_agent(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"Missing frontmatter: {path}")
    front, body = text[4:].split("\n---\n", 1)
    metadata = {}
    for line in front.splitlines():
        key, value = line.split(":", 1)
        value = value.strip()
        metadata[key] = json.loads(value) if value.startswith('"') else value
    if set(metadata) != {"name", "description", "model"}:
        raise ValueError(f"Unexpected metadata: {path}")
    if metadata["name"] != path.stem or not re.fullmatch(r"[a-z][a-z0-9-]*", path.stem):
        raise ValueError(f"Invalid name: {path}")
    if not metadata["description"] or metadata["model"] != "inherit" or not body.strip():
        raise ValueError(f"Incomplete agent: {path}")
    return metadata, body.strip()


def expected_files():
    shared = (ROOT / "shared/working-rules.md").read_text(encoding="utf-8").strip()
    sources = sorted((ROOT / "agents").glob("*.md"))
    if {p.stem for p in sources} != NAMES:
        raise ValueError("Source roster differs from the seven maintained agents")
    result = {}
    for path in sources:
        meta, role = read_agent(path)
        body = role + "\n\n" + shared + "\n"
        header = "---\n" + "\n".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in meta.items()) + "\n---\n\n"
        result[Path(".claude/agents") / path.name] = header + body
        codex = "# Generated by scripts/build.py; edit agents/ and shared/ instead.\n"
        codex += f'name = {json.dumps(meta["name"])}\n'
        codex += f'description = {json.dumps(meta["description"], ensure_ascii=False)}\n'
        # Omitting model and permission settings inherits the host's settings.
        codex += f'developer_instructions = {json.dumps(body, ensure_ascii=False)}\n'
        assert tomllib.loads(codex)["developer_instructions"] == body
        result[Path(".codex/agents") / (path.stem + ".toml")] = codex
    return result


def build(check=False):
    expected = expected_files()
    for folder, suffix in ((".codex/agents", "*.toml"), (".claude/agents", "*.md")):
        extra = {p.relative_to(ROOT) for p in (ROOT / folder).glob(suffix)} - set(expected)
        if extra:
            raise ValueError(f"Unexpected generated agents: {extra}")
    for relative, content in expected.items():
        path = ROOT / relative
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise ValueError(f"Generated file is missing or stale: {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return len(expected)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without changing files")
    args = parser.parse_args()
    try:
        print(f'{"Verified" if args.check else "Built"} {build(args.check)} native definitions (seven agents, two platforms).')
    except (ValueError, OSError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
